spring.zipkin.service.name: 
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://euraka-eureka.micro-service:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://esnode1.es--test:9200
      username: elastic
      password: changeme
spring: 
  cloud: 
    config: 
      allowOverride: true
